services:
  mybunker:
    image: bunkerity/bunkerweb:1.5.9
    ports:
      - 80:8080
      - 443:8443
    environment: 
      - SERVER_NAME=www.example.com # replace with your domain
      - AUTO_LETS_ENCRYPT=yes
      - DISABLE_DEFAULT_SERVER=yes
      - API_WHITELIST_IP=127.0.0.1 10.20.30.0/24
      - MAX_CLIENT_SIZE=10G
      - USE_CLIENT_CACHE=yes
      - SERVE_FILES=no
      - ALLOWED_METHODS=GET|POST|HEAD|COPY|DELETE|LOCK|MKCOL|MOVE|PROPFIND|PROPPATCH|PUT|UNLOCK|OPTIONS
      - X_FRAME_OPTIONS=SAMEORIGIN
      - USE_GZIP=yes
      - BAD_BEHAVIOR_STATUS_CODES=400 401 403 405 444
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://mync
      - LIMIT_REQ_URL_1=/apps
      - LIMIT_REQ_RATE_1=5r/s
      - LIMIT_REQ_URL_2=/apps/text/session/sync
      - LIMIT_REQ_RATE_2=8r/s
      - LIMIT_REQ_URL_3=/core/preview
      - LIMIT_REQ_RATE_3=5r/s
      - |
        CUSTOM_CONF_MODSEC_CRS_nextcloud=
        SecAction \
         "id:900130,\
          phase:1,\
          nolog,\
          pass,\
          t:none,\
          setvar:tx.crs_exclusions_nextcloud=1"
        # WebDAV
        SecAction \
         "id:900200,\
          phase:1,\
          nolog,\
          pass,\
          t:none,\
          setvar:'tx.allowed_methods=GET POST HEAD COPY DELETE LOCK MKCOL MOVE PROPFIND PROPPATCH PUT UNLOCK OPTIONS'"
      - |
        CUSTOM_CONF_MODSEC_nextcloud=
        SecRule REQUEST_FILENAME "@rx ^/remote.php/dav/files/" "id:2000,ctl:ruleRemoveByTag=attack-protocol,ctl:ruleRemoveByTag=attack-generic,nolog"
